#!name=WLOC Personal
#!desc=Patch Apple WLOC network location response for Shadowrocket. Shortcuts: set https://www.icloud.com/shortcuts/a82717d8fdad4e6280866fcf911173f7 clear https://www.icloud.com/shortcuts/f42632d406504f24a2cd163af4fe012f
#!author=local
#!category=Tools

[Script]
Apple WLOC Personal = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/tachikomat/wloc/395fdeb027a74dc296c848df034745d74db86048/dist/response-shadowrocket.js,argument=accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/tachikomat/wloc/395fdeb027a74dc296c848df034745d74db86048/dist/wloc-settings-shadowrocket.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
